<template><div><h1 id="systemd-journald-service-简介" tabindex="-1"><a class="header-anchor" href="#systemd-journald-service-简介"><span>systemd-journald.service 简介</span></a></h1>
<p>以前只有 rsyslogd 的时候，由于 rsyslogd 必须要开机完成且执行了 rsyslogd daemon 后，日志文件才会开始记录。所以，核心还需要自己产生一个 klogd 的服务，才能将系统在开机过程、启动服务的过程中的信息记录下来，然后等 rsyslogd 启动后传送给它处理</p>
<p>有了 systemd 后，由于它是核心唤醒的，又是第一个执行的软件，它可以主动调用 systemd-journald 来协助记录日志文件，因此在开机过程中的所有信息，包括启动服务于服务若启动失败的情况等，都可以直接被记录到 systemd-journald s里</p>
<p>systemd-journald 记录到内存中，再给 rsyslogd 记录到硬盘中</p>
<div class="hint-container tip">
<p class="hint-container-title">提示</p>
<p>linux 的内存在文件系统中也有对应的文件形态在 /run/log/ 下，只是人眼看不懂就是了，重启后，该数据就没有了</p>
</div>
<h2 id="使用-journalctl-观察日志信息" tabindex="-1"><a class="header-anchor" href="#使用-journalctl-观察日志信息"><span>使用 journalctl 观察日志信息</span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line">journalct <span class="token punctuation">[</span>-nrpf<span class="token punctuation">]</span> <span class="token punctuation">[</span>--since TIME<span class="token punctuation">]</span> <span class="token punctuation">[</span>--until TIME<span class="token punctuation">]</span> _optional</span>
<span class="line"></span>
<span class="line">选项与参数：</span>
<span class="line">	预设会显示全部的 log 内容，从旧的输出到最新的信息</span>
<span class="line">	-n：显示最近 n 行的信息，找最新信息时有用</span>
<span class="line">	-r：反向输出，从最新的输出到最旧的输出</span>
<span class="line">	-p：显示后面接的信息重要性排序，前一章讲解的日志级别</span>
<span class="line">	-f：类似 <span class="token function">tail</span> <span class="token parameter variable">-f</span> 功能，持续显示 journal 日志内容</span>
<span class="line">	<span class="token parameter variable">--since</span> --unitl：设置开始与结束时间，只显示某段时间范围内的数据</span>
<span class="line">	<span class="token assign-left variable">_SYSTEMD_UNIT</span><span class="token operator">=</span>unit.service：只输出某个服务的信息</span>
<span class="line">	<span class="token assign-left variable">_COMM</span><span class="token operator">=</span>bash：只输出与 <span class="token function">bash</span> 有关的信息</span>
<span class="line">	<span class="token assign-left variable">_PID</span><span class="token operator">=</span>pid：只输出某个 PID 的信息</span>
<span class="line">	<span class="token assign-left variable">_UID</span><span class="token operator">=</span>uid：只输出某个 uid 的信息</span>
<span class="line">	<span class="token assign-left variable">SYSLOG_FACILITY</span><span class="token operator">=</span><span class="token punctuation">[</span><span class="token number">0</span>-23<span class="token punctuation">]</span>：使用 syslog.h 规范的服务相对应的序号来显示指定数据</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line"><span class="token comment"># 范例 1： 显示目前系统中所有的  journal 日志数据</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl </span></span>
<span class="line">-- Logs begin at Sun <span class="token number">2020</span>-03-15 <span class="token number">20</span>:13:33 CST, end at Mon <span class="token number">2020</span>-03-16 00:50:01 CST. --</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:33 study.centos.mrcode systemd-journal<span class="token punctuation">[</span><span class="token number">90</span><span class="token punctuation">]</span>: Runtime journal is using <span class="token number">7</span>.2M <span class="token punctuation">(</span>max allowed <span class="token number">58</span>.1M, trying to leave <span class="token number">87</span>.</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:33 study.centos.mrcode kernel: Initializing cgroup subsys cpuset</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:33 study.centos.mrcode kernel: Initializing cgroup subsys cpu</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:33 study.centos.mrcode kernel: Initializing cgroup subsys cpuacct</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:33 study.centos.mrcode kernel: Linux version <span class="token number">3.10</span>.0-1062.el7.x86_64 <span class="token punctuation">(</span>mockbuild@kbuilder.bsys.centos.org<span class="token punctuation">)</span> <span class="token punctuation">(</span>gcc ver</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:33 study.centos.mrcode kernel: Command line: <span class="token assign-left variable">BOOT_IMAGE</span><span class="token operator">=</span>/vmlinuz-3.10.0-1062.el7.x86_64 <span class="token assign-left variable">root</span><span class="token operator">=</span>/dev/mapper/centos-r</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:33 study.centos.mrcode kernel: e820: BIOS-provided physical RAM map:</span>
<span class="line"><span class="token comment"># 从当次开机以来的所有数据都会显示出来，通过 less 一页页显示，数据流很大</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># 范例 2：仅显示 2020/03/22 整天、昨天 的数据</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl --since "2020-03-16 00:00:00" --until "2020-03-16 23:59:59"</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl --since today		# 今天</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl --since yesterday --unitl today		# 昨天到今天</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># 范例 3：只招数 crond.service 的数据， 同时只列出最新的 10 行信息</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl _SYSTEMD_UNIT=crond.service -n 10</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># 范例 4：找出 su、login 执行的的日志，同时只列出最新的 10 行数据</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl _COMM=su _COMM=login -n 10</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># 范例 5：找出信息严重等级为 error 的信息</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl -p err</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># 范例 6：找出与登录服务 auth、authpriv 有关的日志文件信息</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl SYSLOG_FACILITY=4 SYSLOG_FACILITY=10</span></span>
<span class="line"><span class="token comment"># 关于  SYSLOG_FACILITY 的对应，参考前面的章节</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用它的 <code v-pre>-f</code> 实时显示功能</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line"><span class="token comment"># 第一个终端机</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl -f</span></span>
<span class="line"><span class="token punctuation">..</span>. 下面的信息是，2 号终端机执行指令后显示的信息</span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/pickup<span class="token punctuation">[</span><span class="token number">14953</span><span class="token punctuation">]</span>: 827B31075: <span class="token assign-left variable">uid</span><span class="token operator">=</span><span class="token number">1000</span> <span class="token assign-left variable">from</span><span class="token operator">=</span><span class="token operator">&lt;</span>mrcode<span class="token operator">></span></span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/cleanup<span class="token punctuation">[</span><span class="token number">20434</span><span class="token punctuation">]</span>: 827B31075: message-id<span class="token operator">=</span><span class="token operator">&lt;</span><span class="token number">20200315171525</span>.827B31075@study.centos.mrcode<span class="token operator">></span></span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/qmgr<span class="token punctuation">[</span><span class="token number">1618</span><span class="token punctuation">]</span>: 827B31075: <span class="token assign-left variable">from</span><span class="token operator">=</span><span class="token operator">&lt;</span>mrcode@study.centos.mrcode<span class="token operator">></span>, <span class="token assign-left variable">size</span><span class="token operator">=</span><span class="token number">449</span>, <span class="token assign-left variable">nrcpt</span><span class="token operator">=</span><span class="token number">1</span> <span class="token punctuation">(</span>queue active<span class="token punctuation">)</span></span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/local<span class="token punctuation">[</span><span class="token number">20436</span><span class="token punctuation">]</span>: 827B31075: <span class="token assign-left variable">to</span><span class="token operator">=</span><span class="token operator">&lt;</span>dmtsai@study.centos.mrcode<span class="token operator">></span>, <span class="token assign-left variable">orig_to</span><span class="token operator">=</span><span class="token operator">&lt;</span>dmtsai<span class="token operator">></span>, <span class="token assign-left variable">relay</span><span class="token operator">=</span>local, <span class="token assign-left variable">delay</span><span class="token operator">=</span><span class="token number">0.02</span>, <span class="token assign-left variable">delays</span><span class="token operator">=</span><span class="token number">0.02</span>/0/0/0, <span class="token assign-left variable">dsn</span><span class="token operator">=</span><span class="token number">5.1</span>.1, <span class="token assign-left variable">status</span><span class="token operator">=</span>bounced <span class="token punctuation">(</span>unknown user: <span class="token string">"dmtsai"</span><span class="token punctuation">)</span></span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/cleanup<span class="token punctuation">[</span><span class="token number">20434</span><span class="token punctuation">]</span>: 87ED81076: message-id<span class="token operator">=</span><span class="token operator">&lt;</span><span class="token number">20200315171525</span>.87ED81076@study.centos.mrcode<span class="token operator">></span></span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/bounce<span class="token punctuation">[</span><span class="token number">20437</span><span class="token punctuation">]</span>: 827B31075: sender non-delivery notification: 87ED81076</span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/qmgr<span class="token punctuation">[</span><span class="token number">1618</span><span class="token punctuation">]</span>: 827B31075: removed</span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/qmgr<span class="token punctuation">[</span><span class="token number">1618</span><span class="token punctuation">]</span>: 87ED81076: <span class="token assign-left variable">from</span><span class="token operator">=</span><span class="token operator">&lt;></span>, <span class="token assign-left variable">size</span><span class="token operator">=</span><span class="token number">2291</span>, <span class="token assign-left variable">nrcpt</span><span class="token operator">=</span><span class="token number">1</span> <span class="token punctuation">(</span>queue active<span class="token punctuation">)</span></span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/local<span class="token punctuation">[</span><span class="token number">20436</span><span class="token punctuation">]</span>: 87ED81076: <span class="token assign-left variable">to</span><span class="token operator">=</span><span class="token operator">&lt;</span>mrcode@study.centos.mrcode<span class="token operator">></span>, <span class="token assign-left variable">relay</span><span class="token operator">=</span>local, <span class="token assign-left variable">delay</span><span class="token operator">=</span><span class="token number">0.01</span>, <span class="token assign-left variable">delays</span><span class="token operator">=</span><span class="token number">0</span>/0/0/0, <span class="token assign-left variable">dsn</span><span class="token operator">=</span><span class="token number">2.0</span>.0, <span class="token assign-left variable">status</span><span class="token operator">=</span>sent <span class="token punctuation">(</span>delivered to mailbox<span class="token punctuation">)</span></span>
<span class="line">Mar <span class="token number">16</span> 01:15:25 study.centos.mrcode postfix/qmgr<span class="token punctuation">[</span><span class="token number">1618</span><span class="token punctuation">]</span>: 87ED81076: removed</span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token comment"># 第二个终端机</span></span>
<span class="line"><span class="token punctuation">[</span>mrcode@study ~<span class="token punctuation">]</span>$ <span class="token builtin class-name">echo</span> <span class="token string">"test"</span> <span class="token operator">|</span> mail <span class="token parameter variable">-s</span> <span class="token string">'test'</span> dmtsai</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="logger-指令的应用" tabindex="-1"><a class="header-anchor" href="#logger-指令的应用"><span>logger 指令的应用</span></a></h2>
<p>journalctl 指令是查阅信息，可以通过 logger 把你的数据存储到文件中，下面介绍最简单的本机信息传递，更多的方法请自行查阅 man logger</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line">logger <span class="token punctuation">[</span>-p 服务名称.等级<span class="token punctuation">]</span> <span class="token string">"信息"</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line"><span class="token comment"># 范例 1： 让 dmtsai 使用 logger 来传送数据到日志文件</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span>$ logger <span class="token parameter variable">-p</span> user.info <span class="token string">"I will check logger command"</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl SYSLOG_FACILITY=1 -n 3</span></span>
<span class="line">-- Logs begin at Sun <span class="token number">2020</span>-03-15 <span class="token number">20</span>:13:33 CST, end at Mon <span class="token number">2020</span>-03-16 01:20:43 CST. --</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:50 study.centos.mrcode spice-vdagent<span class="token punctuation">[</span><span class="token number">1860</span><span class="token punctuation">]</span>: Cannot access vdagent virtio channel /dev/virtio-ports/com.redhat.spi</span>
<span class="line">Mar <span class="token number">15</span> <span class="token number">20</span>:13:50 study.centos.mrcode spice-streaming-agent<span class="token punctuation">[</span><span class="token number">1867</span><span class="token punctuation">]</span>: Failed to <span class="token function">open</span> the streaming device "/dev/virtio-ports/org.sp</span>
<span class="line">Mar <span class="token number">16</span> 01:20:43 study.centos.mrcode mrcode<span class="token punctuation">[</span><span class="token number">13699</span><span class="token punctuation">]</span>: I will check logger <span class="token builtin class-name">command</span></span>
<span class="line"><span class="token comment"># 可以看到这里已经传输到了</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>之前写的 backup.service 服务中，如果使用手动方式来备份，即手动执行 <code v-pre>/backups/backup.sh log</code> 来备份时，通过 logger 记录备份开始时间和结束时间</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># vim /backups/backup.sh</span></span>
<span class="line"><span class="token comment">#!/bin/bash</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">if</span> <span class="token punctuation">[</span> <span class="token string">"<span class="token variable">${1}</span>"</span> <span class="token operator">==</span> <span class="token string">'log'</span> <span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token keyword">then</span></span>
<span class="line">	logger <span class="token parameter variable">-p</span> syslog.info <span class="token string">"backup.sh is starting"</span></span>
<span class="line"><span class="token keyword">fi</span></span>
<span class="line"></span>
<span class="line"><span class="token assign-left variable">source</span><span class="token operator">=</span><span class="token string">"/etc /home /root /var/lib /var/spool/{cron,at,mail}"</span></span>
<span class="line"><span class="token assign-left variable">target</span><span class="token operator">=</span><span class="token string">"/backups/backup-system-<span class="token variable"><span class="token variable">$(</span><span class="token function">date</span> +%Y-%m-%d<span class="token variable">)</span></span>.tar.gz"</span></span>
<span class="line"></span>
<span class="line"><span class="token punctuation">[</span> <span class="token operator">!</span> <span class="token parameter variable">-d</span> /backups <span class="token punctuation">]</span> <span class="token operator">&amp;&amp;</span> <span class="token function">mkdir</span> /backups</span>
<span class="line"></span>
<span class="line"><span class="token function">tar</span> <span class="token parameter variable">-zcvf</span> <span class="token variable">${target}</span> <span class="token variable">${source}</span> $<span class="token operator">></span> /backups/backup.log</span>
<span class="line"></span>
<span class="line"><span class="token keyword">if</span> <span class="token punctuation">[</span> <span class="token string">"<span class="token variable">${1}</span>"</span> <span class="token operator">==</span> <span class="token string">'log'</span> <span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token keyword">then</span></span>
<span class="line">	logger <span class="token parameter variable">-p</span> syslog.info <span class="token string">"backup.sh is finished"</span></span>
<span class="line"><span class="token keyword">fi</span></span>
<span class="line"></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># /backups/backup.sh log</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># journalctl SYSLOG_FACILITY=5 -n 3</span></span>
<span class="line">-- Logs begin at Sun <span class="token number">2020</span>-03-15 <span class="token number">20</span>:13:33 CST, end at Mon <span class="token number">2020</span>-03-16 01:28:54 CST. --</span>
<span class="line">Mar <span class="token number">16</span> 00:42:45 study.centos.mrcode rsyslogd<span class="token punctuation">[</span><span class="token number">7107</span><span class="token punctuation">]</span>:  <span class="token punctuation">[</span>origin <span class="token assign-left variable">software</span><span class="token operator">=</span><span class="token string">"rsyslogd"</span> <span class="token assign-left variable">swVersion</span><span class="token operator">=</span><span class="token string">"8.24.0-38.el7"</span> x-pid<span class="token operator">=</span><span class="token string">"7107"</span> x-info</span>
<span class="line">Mar <span class="token number">16</span> 01:28:27 study.centos.mrcode mrcode<span class="token punctuation">[</span><span class="token number">17659</span><span class="token punctuation">]</span>: backup.sh is starting</span>
<span class="line">Mar <span class="token number">16</span> 01:28:54 study.centos.mrcode mrcode<span class="token punctuation">[</span><span class="token number">19555</span><span class="token punctuation">]</span>: backup.sh is finished</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>也就是说，该指令是类似一个日志服务接口，我们可以通过它把日志信息记录下来</p>
<h2 id="保存-journal-的方式" tabindex="-1"><a class="header-anchor" href="#保存-journal-的方式"><span>保存 journal 的方式</span></a></h2>
<p>systemd-journald.service 的信息在内存中，而持久化到硬盘的数据是通过 rsyslogd 来做的，如果你想要保存下 journald 处理的数据，可以通过如下的方式</p>
<p>基本上 systemd-journald.service 的配置文件主要参考 <code v-pre>/etc/systemd/journald.conf</code> 的内容，默认配置基本上满足需求，如有定制信息，请通过 man 5 journald.conf 查阅</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line"><span class="token comment"># 1. 处理所需要的目录与相关权限设置</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># mkdir /var/log/journal</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># chown root:systemd-journal /var/log/journal/</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># chmod 2775 /var/log/journal/</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># 2. 重新启动 systemd-journald 并观察备份的日志数据</span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># systemctl restart systemd-journald.service </span></span>
<span class="line"><span class="token punctuation">[</span>root@study ~<span class="token punctuation">]</span><span class="token comment"># ll /var/log/journal/</span></span>
<span class="line">total <span class="token number">0</span></span>
<span class="line">drwxr-sr-x. <span class="token number">2</span> root systemd-journal <span class="token number">28</span> Mar <span class="token number">16</span> 01:35 f228ab37c368416c84c6b27971ba45a9</span>
<span class="line"></span>
<span class="line"><span class="token comment"># 配置预设的目录后，服务重启后，会自动复制一份到该目录下</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>作者建议；有 rsyslog.service 以及 logrotate 的存在，所以这里产生的信息可以不用存档</p>
</div></template>


